<?php
$model="wirausaha";
$url="kelolaAdminSPW";
$columns=['no','nama','aksi'];
$tambah=true;
$role="wirausaha";
$inputs=[
    'nama'=>[
        'email'
      ],
    'type'=>[
      'email'
    ],
    'name'=>[
            'email'
    ],
    'placeholder'=>
    [
        'email'
    ],
    'value'=>[''],
    'required'=>['required']
];
?>
@extends('layouts.app')
@section('var')
form=['nama','password'];
data = [
  {
    'data':'1',
    render: function (data, type, row, meta) {
        return meta.row + meta.settings._iDisplayStart + 1;
    }
},
    {
        'data':'name','name':'name'
    },
    {
        'data':'aksi','name':'aksi'
    }
]
@endsection